# Keeper of the Seeds - Gas Town Plugin Manifest
name: keeper
version: 1.2.0
description: |
  Governance plugin for architectural consistency. Prevents drift by enforcing
  reuse over creation through a dual-gate system:
  - Front gate (Mayor): Reviews specs before work is assigned
  - Back gate (Refinery): Validates changes before merge
type: governance

author: "Jeremy Kalmus"
repository: "https://github.com/jeremykalmus/keeper"

# Compatibility
gastown_version: ">=0.2.0"
requires: []

# Installation
install:
  # Primary installation method: shell script
  script: "./install/install-keeper.sh"

  # Script options
  options:
    mode:
      description: "Initial Keeper mode"
      type: string
      enum: [seeding, growth, conservation]
      default: growth
    force:
      description: "Overwrite existing files"
      type: boolean
      default: false

  # What gets installed
  creates:
    - keeper/keeper.yaml
    - keeper/seeds/frontend.yaml
    - keeper/seeds/backend.yaml
    - keeper/seeds/data.yaml
    - keeper/seeds/auth.yaml
    - keeper/seeds/config.yaml
    - keeper/seeds/testing.yaml
    - keeper/decisions/
    - keeper/hooks/keeper-gate.sh
    - keeper/KEEPER-INSTRUCTIONS.md

  # Slash commands installed
  commands:
    - source: commands/keeper-plant.md
      targets:
        - mayor/.claude/commands/
        - .claude/commands/
    - source: commands/keeper-review.md
      targets:
        - mayor/.claude/commands/
        - .claude/commands/
    - source: commands/keeper-validate.md
      targets:
        - refinery/.claude/commands/
        - .claude/commands/
    - source: commands/keeper-tend.md
      targets:
        - mayor/.claude/commands/
        - .claude/commands/
    - source: commands/keeper-prune.md
      targets:
        - mayor/.claude/commands/
        - .claude/commands/

# Uninstallation
uninstall:
  script: "./install/uninstall-keeper.sh"
  options:
    keep-decisions:
      description: "Preserve existing ADRs"
      type: boolean
      default: false
    keep-seeds:
      description: "Preserve seed files"
      type: boolean
      default: false

# Slash commands provided
commands:
  keeper-plant:
    description: "Discover existing patterns and populate Seed Vault (run once after install)"
    usage: "/keeper-plant [--mode seeding|growth]"
    for: [mayor, crew]
    file: commands/keeper-plant.md

  keeper-review:
    description: "Review spec against Seed Vault before creating beads"
    usage: "/keeper-review <spec-file-or-description>"
    for: [mayor, crew]
    file: commands/keeper-review.md

  keeper-validate:
    description: "Validate polecat changes against keeper_decision before merge"
    usage: "/keeper-validate <adr-id-or-branch>"
    for: [refinery]
    file: commands/keeper-validate.md

  keeper-tend:
    description: "Lightweight incremental seed maintenance - check recent changes"
    usage: "/keeper-tend [--days N] [--mode seeding|growth]"
    for: [mayor, crew]
    file: commands/keeper-tend.md

  keeper-prune:
    description: "Analyze codebase for redundancy, generate consolidation recommendations"
    usage: "/keeper-prune [--category components|services|types|routes]"
    for: [mayor, crew]
    file: commands/keeper-prune.md

# Configuration schema
config_schema:
  type: object
  properties:
    mode:
      type: string
      enum: [seeding, growth, conservation]
      default: growth
      description: |
        Keeper strictness mode based on project maturity:
        - seeding: Early project, allows new seeds freely
        - growth: Default, reuse-first, extensions preferred
        - conservation: Mature project, new seeds rarely approved
  required: []

# Integration architecture
integration:
  # Front gate: Mayor reviews before creating beads
  front_gate:
    when: "Before Mayor creates beads/convoy"
    who: Mayor
    command: "/keeper-review <spec>"
    output: "keeper/decisions/NNN-<name>.yaml"
    blocks_if: "status != approved"

  # Back gate: Refinery validates before merge
  back_gate:
    when: "Before Refinery merges polecat PR"
    who: Refinery
    command: "/keeper-validate <adr-id>"
    blocks_if: "violations > 0"

# Documentation
docs:
  spec: keeper-spec.md
  readme: README.md
